# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Provide a fullNameOverride
fullNameOverride:
config:
  #should contain the port number for HTTP protocol
  #E.g. port: 80
  port: 4000
  #E.g. logLevel: info
  logLevel: info  
  enableLivenessProbe: false
  inteliApiAddr: 
  logo: 
  kinaxisUrl: 
  persona:

auth:
  enabled: false
  frontendDomain: 
  frontendScope:
  inteliApiAudience:

ingress: 
  enabled: false
  # annotations:
  #   kubernetes.io/ingress.global-static-ip-name: inteli-poc-web
  #   networking.gke.io/managed-certificates: inteli-poc-managed-cert
  #   kubernetes.io/ingress.class: "gce"
  # className: "gce"
  paths:
    - /

# eg. replicaCount: 1
replicaCount: 1

# image section provides the information about the image used
# eg. repository: ghcr.io/inteli-poc/inteli-frontend
image:
  repository: ghcr.io/inteli-poc/inteli-frontend
  pullPolicy: IfNotPresent
  tag: 'latest'
  # The kubernetes secret used to access the image
  pullSecrets: regcred

# This section contains the vault related information.
# NOTE: Make sure that the vault is already unsealed, intialized and configured to
# use the Kubernetes service account token based authentication.
vault:
  # for eg. alpineutils: ghcr.io/hyperledger/bevel-alpine:latest #this image has curl installed
  alpineutils:
  # address provide the vault address
  # Eg. address: http://vault.example.com:8200
  address:
  # secretprefix provide the vault path where the secrets are stored
  # Eg. secretPrefix: secretsv2/sub-org-name
  secretprefix:
  # serviceaccountname provide the service account name authenticated to vault.
  # NOTE: Make sure that the service account is already created and authenticated to use the vault.
  # Eg. serviceaccountname: vault-auth
  serviceaccountname:
  # role provide the vault role used.
  # Eg. appRole: vault-role
  role:
  # authPath provide the auth path configured to be used. Default is /kubernetes
  authpath:

# This will be the proxy/ingress provider. Can have values "ambassador" or "haproxy"
# Eg. provider: "ambassador"
proxy:
  provider:
  # This will be the name of the organization
  # Eg. name: carrier
  name:
  # External URL of the organization
  # Eg. external_url_suffix: test.inteli.example.com
  external_url_suffix:
  # provide the external port
  port: 443
  # Provide the tag for certificate issuer
  issuedFor: 
